### ISSUE TITLE
GTexture.dispose works wrong/contains bugs

### ISSUE THREAD

**Issue by gNikro** [pshtif/Genome2D-ContextFlash#9]
- 1. [override public function dispose(p_disposeSource:Bool = false):Void {
](https://github.com/pshtif/Genome2D-ContextFlash/blob/master/src/com/genome2d/textures/GTexture.hx#L193)

when it call [super](https://github.com/pshtif/Genome2D-ContextCommon/blob/master/src/com/genome2d/textures/GTextureBase.hx#L357) it always set source to NULL even if we pass disposeSource as FALSE

- 2. GTextureBase.dispose() is call onInvalidated.removeAll(); so after that we cant restore subTextures of that texture
E.G if i dispose texture with disposeSource FALSE, that texture should keep source and should be restored after i call invalidateNativeTexture, but subTextures is no longer subscribed to g2d_onInvalidated. "Main texture" will be restored but sub textures is not.

**Comment by pshtif** [comment]
You misinterpret the paramter disposeSource, it works as designed what it means it will not dispose the underlying source the texture was generated from (BitmapData, ByteArray...) but it still disposes the texture itself and dereferences itself from the source to avoid reference islands.

You want to achieve something entirely different, disposing just the GPU part of the texture instead of the actual GTexture instance.

**Comment by gNikro** [comment]
Yes i got it
